apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-apps-backup
spec:
  schedule: "0 0 * * *" # daily
  # schedule: "* * * * *" # every minute for testing
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: google/cloud-sdk:latest
              envFrom:
                - configMapRef:
                    name: postgres-config
                - secretRef:
                    name: postgres-secret
              volumeMounts:
                - name: gcs-key
                  mountPath: /secrets
                  readOnly: true

              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Installing PostgreSQL client..."
                  export DEBIAN_FRONTEND=noninteractive

                  # Update package lists and install prerequisites
                  apt-get update && apt-get install -y wget ca-certificates gnupg2 curl

                  # Add the PostgreSQL APT repository key
                  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

                  # Add the PostgreSQL 16 repository to your sources list
                  # The google/cloud-sdk image is based on a Debian or Ubuntu variant, lsb_release -cs finds the codename (e.g., "bookworm" or "noble")
                  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

                  # Update apt package lists again to include the new repository
                  apt-get update

                  # Install the PostgreSQL 16 client
                  apt-get install -y postgresql-client-16


                  echo "Authenticating to GCP..."
                  gcloud auth activate-service-account --key-file=/secrets/key.json
                  gcloud config set project kube-mooc

                  export PGPASSWORD="$POSTGRES_PASSWORD"

                  TIMESTAMP=$(date +"%Y-%m-%d-%H-%M")
                  FILE="/tmp/todo-apps-$TIMESTAMP.sql"

                  echo "Running pg_dump..."
                  pg_dump \
                    -h "$POSTGRES_HOST" \
                    -U "$POSTGRES_USER" \
                    -d "$POSTGRES_DB" \
                    > "$FILE"

                  echo "Uploading backup to GCS..."
                  gsutil cp "$FILE" "gs://kube-mooc-bucket/todo-apps-$TIMESTAMP.sql"

                  echo "Backup completed."

          volumes:
            - name: gcs-key
              secret:
                secretName: gcs-key
