apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hourly-image-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CUPAXX/kubernetestraining.git
    targetRevision: master
    path: hourly-image/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
