apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-apps-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CUPAXX/kubernetestraining.git
    targetRevision: master
    path: todo-apps/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
